// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDhmouADOjz-3dqzNTIzNmSpBbLD9VVbIU',
    appId: '1:713766077615:web:34fcdae59909e894f8005a',
    messagingSenderId: '713766077615',
    projectId: 'myauthentication-3c46e',
    authDomain: 'myauthentication-3c46e.firebaseapp.com',
    storageBucket: 'myauthentication-3c46e.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAvB7fz71-0hlZ43hhJe4OBJNIp1SJnMRg',
    appId: '1:713766077615:android:fce667f1f9af5799f8005a',
    messagingSenderId: '713766077615',
    projectId: 'myauthentication-3c46e',
    storageBucket: 'myauthentication-3c46e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD1Wsyvj4DjOXI-JSK2o_gEf61LMNxZGIs',
    appId: '1:713766077615:ios:a7596fbc7dfe7f9ff8005a',
    messagingSenderId: '713766077615',
    projectId: 'myauthentication-3c46e',
    storageBucket: 'myauthentication-3c46e.firebasestorage.app',

    iosBundleId: 'com.example.authentication',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD1Wsyvj4DjOXI-JSK2o_gEf61LMNxZGIs',
    appId: '1:713766077615:ios:a7596fbc7dfe7f9ff8005a',
    messagingSenderId: '713766077615',
    projectId: 'myauthentication-3c46e',
    storageBucket: 'myauthentication-3c46e.firebasestorage.app',

    iosBundleId: 'com.example.authentication',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDhmouADOjz-3dqzNTIzNmSpBbLD9VVbIU',
    appId: '1:713766077615:web:b4cfdf8bd26476d4f8005a',
    messagingSenderId: '713766077615',
    projectId: 'myauthentication-3c46e',
    authDomain: 'myauthentication-3c46e.firebaseapp.com',
    storageBucket: 'myauthentication-3c46e.firebasestorage.app',
  );
}