// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBoV4xt-PQremb31_JwEzMCWRhNSu8VaYk',
    appId: '1:1048299694129:web:edeeec848ba465fb8ccd10',
    messagingSenderId: '1048299694129',
    projectId: 'crud-c08ac',
    authDomain: 'crud-c08ac.firebaseapp.com',
    storageBucket: 'crud-c08ac.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCN0V9KXWahj8oGCkWWGtIxf1DVCbMI_y4',
    appId: '1:1048299694129:android:0935ffa3ca24568e8ccd10',
    messagingSenderId: '1048299694129',
    projectId: 'crud-c08ac',
    storageBucket: 'crud-c08ac.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA_NIHP8Aiwacj25Esd6tenTV2y8jZBggE',
    appId: '1:1048299694129:ios:601a63d82b49be8a8ccd10',
    messagingSenderId: '1048299694129',
    projectId: 'crud-c08ac',
    storageBucket: 'crud-c08ac.firebasestorage.app',
    iosBundleId: 'com.example.database',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA_NIHP8Aiwacj25Esd6tenTV2y8jZBggE',
    appId: '1:1048299694129:ios:601a63d82b49be8a8ccd10',
    messagingSenderId: '1048299694129',
    projectId: 'crud-c08ac',
    storageBucket: 'crud-c08ac.firebasestorage.app',
    iosBundleId: 'com.example.database',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBoV4xt-PQremb31_JwEzMCWRhNSu8VaYk',
    appId: '1:1048299694129:web:c034e53c06da9e5b8ccd10',
    messagingSenderId: '1048299694129',
    projectId: 'crud-c08ac',
    authDomain: 'crud-c08ac.firebaseapp.com',
    storageBucket: 'crud-c08ac.firebasestorage.app',
  );
}
